#!/usr/bin/env python3
"""Render the Network-as-Code data model from lab.env.

The NaC module is inventory driven: the configuration is a YAML document, not a
set of Terraform resources. Addressing still belongs in lab.env, so the document
is generated rather than hand-maintained -- otherwise the lab would have two
places that both claim to know which port reaches which router.

Note the shape of the interface entry. The address lives under `ipv4:`, not at
the top level. The module reads every optional key through try(), so a key at
the wrong depth is not an error: it is silently dropped, the plan succeeds, and
a loopback is created with no address on it.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from provision import load_env, routers  # noqa: E402

LAB_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(LAB_DIR, "terraform-nac", "iosxe.nac.yaml")

LOOPBACK_ID = 98
ACL_NAME = "NAC-MANAGED"
DESCRIPTION = "Managed by Network as Code"


def model(env):
    devices = []
    for i, r in enumerate(routers(env), start=1):
        devices.append({
            "name": r,
            # NETCONF, not RESTCONF. The NaC module requires iosxe provider
            # >= 1.0.0, and 1.0.0 removed RESTCONF support entirely -- there is
            # no protocol or url attribute left on it, and the default port is
            # 830. The hand-written configuration in ../terraform still uses
            # RESTCONF because it pins the 0.x provider.
            "host": f"127.0.0.1:{env[f'{r}_NETCONF']}",
            "configuration": {
                "interfaces": {
                    "loopbacks": [{
                        "id": LOOPBACK_ID,
                        "description": DESCRIPTION,
                        "ipv4": {
                            "address": f"10.98.{i}.1",
                            "address_mask": "255.255.255.255",
                        },
                    }],
                },
                "access_lists": {
                    "standard": [{
                        "name": ACL_NAME,
                        "entries": [
                            {"sequence": 10, "remark": DESCRIPTION},
                            {"sequence": 20, "action": "permit",
                             "prefix": "10.98.0.0", "prefix_mask": "0.0.255.255"},
                            {"sequence": 30, "action": "deny", "any": True},
                        ],
                    }],
                },
            },
        })
    return {"iosxe": {"devices": devices}}


def main():
    try:
        import yaml
    except ImportError:
        sys.exit("PyYAML is required to render the NaC model")
    env = load_env()
    with open(OUT, "w") as fh:
        fh.write("# Generated by tools/nac_yaml.py from lab.env -- do not edit by hand.\n")
        yaml.safe_dump(model(env), fh, sort_keys=False, default_flow_style=False)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
